### ISSUE TITLE
when I  run the './bin/pseudo-distribute.sh etc/p2a3.json'

### ISSUE THREAD

**Issue by cristicVictory** [gryadka/js-example#1]
when I  run the './bin/pseudo-distribute.sh etc/p2a3.json', there always has some error.
./bin/pseudo-distribute.sh: line 10: node-nightly: command not found
./bin/pseudo-distribute.sh: line 11: node-nightly: command not found

**Comment by rystsov** [comment]
Gryadka relies on the async/await feature of ES7, so you need either to run it on the latest version of node.js or to use transpilers like Babel. I tried to use Babel but found the modification of the source creates an extra friction in the development process so I switched to the nightly builds of node.js.

You can find instructions how to install node-nightly there: https://www.npmjs.com/package/node-nightly
